apiVersion: v2
name: sitecore930-xm
description: A Sitecore 9.3.0 XM Helm chart for Kubernetes
icon: https://mygetwwwsitecoreeu.blob.core.windows.net/feedicons/sc-packages.png?202004140646
type: application
kubeVersion: ">= 1.15.0"
version: 1.0.0
appVersion: 9.3.0
keywords:
  - sitecore
  - cms
  - windows
  - experience
home: https://github.com/sitecoreops/sitecore-helm
sources:
  - https://github.com/sitecoreops/sitecore-helm/tree/master/charts/sitecore930-xm
maintainers:
  - name: Per Bering
    url: https://github.com/pbering/